spring:
  datasource:
    url: jdbc:mysql://localhost:3306   # 데이터베이스 URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root                           # 데이터베이스 사용자 이름
    password: 1234                           # 데이터베이스 암호

# 서버 설정
server:
  port: 8080                    # 애플리케이션이 실행될 포트

  jpa:
    hibernate:
      ddl-auto: create          # Hibernate가 데이터베이스 스키마를 자동으로 생성/업데이트하는 옵션
    show-sql: true

# 로깅 설정
logging:
  level:
    root: info                 # 전체 로그 레벨 설정
    org.springframework: info  # 스프링 프레임워크 패키지의 로그 레벨 설정
    com.example: debug         # 특정 패키지나 클래스의 로그 레벨 설정


jwt:
  secret-key: bWVnYWR4LWRtcC1zZXJ2aWNlLWRldmVsb3Atc2VjdXJpdHkta2V5LXZhbHVlLTIzMDEzMQ==
  # access token valid time (1시간) 60 * 60 * 1000
  access-valid-time: 3600000
  # refresh token valid time (30일) 60 * 60 * 24 * 30 * 1000
  refresh-valid-time: 2592000000